apiVersion : apps/v1
kind: Deployment
metadata:
  name: weather-collector-deployment
  labels:
    app: spring-cloud-weather-forecasting-weather-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      project: spring-cloud-weather-forecasting-weather-collector
  template:
    metadata:
      labels:
        project: spring-cloud-weather-forecasting-weather-collector
    spec:
      containers:
        - name: weather-collector
          image: ivangorbunovv/spring-cloud-weather-forecasting:weather-collector
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: weather-collector
  labels:
     env  : dev
     owner: IvanGorbunov
spec:
  selector:
    project: spring-cloud-weather-forecasting-weather-collector
  ports:
    - name      : weather-collector-listener
      protocol  : TCP
      port      : 8081
      targetPort: 8081
  #type: CLusterIP