apiVersion : apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: spring-cloud-weather-forecasting-postgres
spec:
  replicas: 1 #2
  selector:
    matchLabels:
      project: spring-cloud-weather-forecasting-postgres
  template:
    metadata:
      labels:
        project: spring-cloud-weather-forecasting-postgres
    spec:
      containers:
        - name : postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "root"
            - name: POSTGRES_DB
              value: "spring-cloud-weather-forecasting-data-consumer-to-db"
          readinessProbe:
            exec:
              command:
                - "pg_isready"
                - "-U"
                - "postgres"
                - "-d"
                - "spring-cloud-weather-forecasting-data-consumer-to-db"
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  labels:
     env  : dev
     owner: IvanGorbunov
spec:
  selector:
    project: spring-cloud-weather-forecasting-postgres
  ports:
    - name      : postgres-listener
      protocol  : TCP
      port      : 5432
      targetPort: 5432
  #type: CLusterIP
