apiVersion : apps/v1
kind: Deployment
metadata:
  name: eureka-server-deployment
  labels:
    app: spring-cloud-weather-forecasting-eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      project: spring-cloud-weather-forecasting-eureka-server
  template:
    metadata:
      labels:
        project: spring-cloud-weather-forecasting-eureka-server
    spec:
      containers:
        - name: eureka-server
          image: ivangorbunovv/spring-cloud-weather-forecasting:eureka-server
          ports:
            - containerPort: 8761

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  labels:
     env  : dev
     owner: IvanGorbunov
spec:
  selector:
    project: spring-cloud-weather-forecasting-eureka-server
  ports:
    - name      : eureka-server-listener
      protocol  : TCP
      port      : 8761
      targetPort: 8761
  #type: CLusterIP